# Generated by Django 5.0.6 on 2024-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_review_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
